queue_rules:
  - name: default
    conditions:
      - 'check-success=ci/circleci: job_required_for_mergify'
pull_request_rules:
  - name: automatically merge scala-steward's minor version PRs
    conditions:
      - author=kaluza-libraries
      - body~=labels:.*semver-minor
      - 'check-success=ci/circleci: job_required_for_mergify'
    actions:
      review:
        type: APPROVE
      queue:
        name: default
      delete_head_branch: {}
  - name: automatically merge scala-steward's patch version PRs
    conditions:
      - author=kaluza-libraries
      - body~=labels:.*semver-patch
      - 'check-success=ci/circleci: job_required_for_mergify'
    actions:
      review:
        type: APPROVE
      queue:
        name: default
      delete_head_branch: {}
